name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with GCC
        shell: bash
        run: |
          TARGET_OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          TARGET_ARCH=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')

          EXT=""
          if [ "$TARGET_OS" = "windows" ]; then
            EXT=".exe"
          fi

          OUTPUT_NAME="etml-${TARGET_OS}-${TARGET_ARCH}${EXT}"

          mkdir -p compiler/bin
          
          gcc -o "compiler/bin/${OUTPUT_NAME}" compiler/etml.c

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ runner.os }}-${{ runner.arch }}
          path: compiler/bin/etml-*
